Update install

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -39,6 +39,20 @@ cd ${OPENSHIFT_DATA_DIR}.mysql
 rm ${OPENSHIFT_DATA_DIR}.mysql/bin/{mysql_install_db,mysql_ssl_rsa_setup}
 
 # Add DB_HOST and DB_PORT environment variables
+echo 'Generating username and password'
+
+env_dir="${OPENSHIFT_MYSQL_DIR}/env"
+username=$(generate_username)
+password=$(generate_password)
+
+set_env_var 'OPENSHIFT_MYSQL_DB_USERNAME' "$username" $env_dir
+set_env_var 'OPENSHIFT_MYSQL_DB_PASSWORD' $password $env_dir
+set_env_var 'OPENSHIFT_MYSQL_DB_URL' "mysql://$username:$password@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/" $env_dir
+set_env_var 'OPENSHIFT_MYSQL_VERSION' $version $env_dir
+
+echo 'Installing mysqld'
+
+mysql_data_dir="${OPENSHIFT_MYSQL_DIR}/data"
 if [ -z "$OPENSHIFT_MYSQL_PROXY_PORT" ]; then
   # Since $OPENSHIFT_MYSQL_PROXY_PORT is missing, cartridge must be running in the main gear
   echo "$OPENSHIFT_MYSQL_DB_HOST" > $OPENSHIFT_MYSQL_DIR/env/DB_HOST
@@ -50,6 +64,23 @@ else
 fi
 
 # Output result
-client_result "MySQL ${2} installed."
-client_result "The initial root password will be set to 'root', make sure to change it!"
-client_result "Use \$DB_HOST and \$DB_PORT environment variables to connect your application."
+# Must be invoked with absolute path to avoid a mysql bug involving my_print_defaults
+mysql_context "/usr/bin/mysql_install_db --datadir=${mysql_data_dir} --skip-name-resolve --force &>/tmp/mysql_install_db.log" || error 'Failed to create mysqldb', 119
+
+client_result ""
+client_result "MySQL ${version} database added.  Please make note of these credentials:"
+client_result ""
+client_result "       Root User: $username"
+client_result "   Root Password: $password"
+client_result "   Database Name: $OPENSHIFT_APP_NAME"
+client_result ""
+
+client_result 'Connection URL: mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/'
+client_result ""
+client_result "You can manage your new MySQL database by also embedding phpmyadmin."
+client_result "The phpmyadmin username and password will be the same as the MySQL credentials above."
+
+cart_props 'connection_url=mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/'
+cart_props "username=$username"
+cart_props "password=$password"
+cart_props "database_name=$OPENSHIFT_APP_NAME"
